name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v4

      - name: Bun setup
        uses: oven-sh/setup-bun@v2

      - name: Build
        run: |
          bun install
          bun run lint
          bun run build:release

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            manifest.json dist/styles.css dist/main.js
